modLoader="javafml"
loaderVersion="[36,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/starforcraft/Centrifuge-Tiers/issues/new/choose"
[[mods]]
modId="ctiers"
version="${file.jarVersion}"
displayName="Centrifuge Tiers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/centrifuge-tiers"
logoFile="examplemod.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds tiers to the Centrifuge."

[[dependencies.ctiers]]
    modId="resourcefulbees"
    mandatory=true
    versionRange="[0.5.9b,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ctiers]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ctiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"